name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vercel_deployment_preview:
    name: Setup testing environment preview
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 300
      - run: "echo deployment url is ready: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}"
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    needs: vercel_deployment_preview
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install
      - name: Run tests
        run: timeout 300 npm run test-e2e-start-server || exit 1
        env:
          # running against localhost atm - not needed for the moment
          # PLAYWRIGHT_TEST_BASE_URL: ${{ needs.vercel_deployment_preview.outputs.preview_url }}
          # no need to redeclare again, in the playwright config localhost:3000 is already set as fallback
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: "test"
          NEXT_PUBLIC_IMAGEKIT_URL: "https://ik.imagekit.io"
          NEXTAUTH_SECRET: "mocked_nextauth_secret"
          NEXTAUTH_URL: "http://localhost:3000"
          PINECONE_NAMESPACE: "mocked_pinecone_namespace"
          DISCORD_CLIENT_ID: "mocked_discord_client_id"
          DISCORD_CLIENT_SECRET: "mocked_discord_client_secret"


